freebsd_task:
  freebsd_instance:
    image: freebsd-12-1-release-amd64
    cpu: 4
    memory: 8GB
  install_script:
    - uname -a
    - pkg install -y python27 py27-cffi py27-coverage python37 py37-cffi py37-coverage bash
  build_script:
    - python2.7 setup.py build
    - python3.7 setup.py build
  test_script:
    - python2.7 setup.py test
    - python3.7 setup.py test
  coverage_script:
    # There is definitely some redundancy with test_script here.
    - python2.7 covrunner.py
    - python3.7 covrunner.py
    - coverage-3.7 xml
    - fetch -o u.sh https://codecov.io/bash
    - bash u.sh -t "b7185a33-b156-402f-9a1d-b47dfd2f69bd"
